# Cloudflare Pages configuration
name = "blockeddrainsinaldershot-co-uk"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-20"

[[d1_databases]]
binding = "DB"
database_name = "aldershot-leads"
database_id = "d19cee02-ab14-4e26-9083-b1d556805c57"
